import Clock from "@/components/Clock";
import "./globals.css";
import Header from "@/components/Header";

export const metadata = {
  title: " Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
      >
        <Header/>
        {children}
          <Clock/> 
      </body>
    </html>
  );
}
